# .github/workflows/frontend-ci.yml
name: Frontend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Klona repot
      uses: actions/checkout@v3

    - name: Installera Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Installera beroenden och bygg projektet
      run: |
        cd frontend
        npm install
        npm run build
